---
title: "Landscape ruggedness, random codon assignment codes"
output: html_document
date: "2023-01-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
library(stringr)
library(ggpubr)
```


# GB1
```{r}
results = read.delim("output/results/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", "NumPeaks", "MeanPeakHeight", "NoEpi", "MagEpi", "SsEpi", "RsEpi", "PropAccPaths")
```

# Number of peaks
```{r}
cor.test(results$Robustness[2:100000], results$NumPeaks[2:100000])
```

# Epistasis
#### No epistasis
```{r}
cor.test(results$Robustness[2:100000], results$NoEpi[2:100000])
```

#### Magnitude
```{r}
cor.test(results$Robustness[2:100000], results$MagEpi[2:100000])
```

#### Simple-sign
```{r}
cor.test(results$Robustness[2:100000], results$SsEpi[2:100000])
```

#### Reciprocal-sign
```{r}
cor.test(results$Robustness[2:100000], results$RsEpi[2:100000])
```

# Mutational accessibility
```{r}
cor.test(results$Robustness, results$PropAccPaths)

res_size = read.delim("02_01_global_peak_size/results_globalPeakSize_random", header=FALSE)
colnames(res_size) = c("Seed", "SummitSize")
results = merge(results, res_size)

# restrict the analysis to those codes that preserve the size of the global peak
tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0] ,]
nrow(tmp_res)

cor.test(tmp_res$Robustness, tmp_res$PropAccPaths)
```



# Plot: comparison of the robustness of aa permutation and random codon assignment codes
```{r}
results_aaperm = read.delim("../aa_permutation/output/results/results", header=FALSE)
colnames(results_aaperm)[3]="Robustness"
mean(results$Robustness[2:100000])
mean(results_aaperm$Robustness[2:100000])
(test = t.test(results$Robustness[2:100000], results_aaperm$Robustness[2:100000]))


data_plotting = data.frame(Robustness = c(results$Robustness[2:100000], results_aaperm$Robustness[2:100000]),
                           Randomization = c(rep("Random codon assignment", 99999), rep("Amino acid permutation", 99999)))
ggplot(data_plotting, aes(x=Robustness, fill=Randomization, color=Randomization)) +
  geom_histogram(alpha=0.5) +
  theme_test() + scale_fill_grey() + scale_color_grey() + 
  theme(legend.position="bottom") + labs(y="Count")
```