---
title: "ParE2, random codon assignment codes, random walk"
author: "Hana Rozhonova"
date: "6/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(gridExtra)
```

# Read the data
```{r}
results = read.delim("output/results_10000/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", paste0("Fitness_", seq(0,990,by=10)))
```


# Correlations between code robustness and mean fitness
```{r}
cor.test(results$Robustness[2:100000], results$Fitness_500[2:100000])
```

Correct for global peak size:
```{r}
res_size = read.delim("../../02_ruggedness/random_codon_assignment/02_01_global_peak_size/results_globalPeakSize_random", header=FALSE)
colnames(res_size) = c("Seed", "SummitSize")
results = merge(results, res_size)

tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0],]
nrow(tmp_res)

(corTest = cor.test(tmp_res$Robustness, tmp_res$Fitness_500))
```

Repeat the analysis for N=10, N=100 and N=1,000,000:

# N=10
```{r}
results = read.delim("output/results_10/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", paste0("Fitness_", seq(0,970,by=10)))
```

Correlation with code robustness:
```{r}
cor.test(results$Robustness[2:100000], results$Fitness_500[2:100000])
```

Correct for global peak size:
```{r}
results = merge(results, res_size)

tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0],]
nrow(tmp_res)

(corTest = cor.test(tmp_res$Robustness, tmp_res$Fitness_500))
```

# N=100
```{r}
results = read.delim("output/results_100/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", paste0("Fitness_", seq(0,970,by=10)))
```

Correlation with code robustness:
```{r}
cor.test(results$Robustness[2:100000], results$Fitness_500[2:100000])
```

Correct for global peak size:
```{r}
results = merge(results, res_size)

tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0],]
nrow(tmp_res)

(corTest = cor.test(tmp_res$Robustness, tmp_res$Fitness_500))
```

# N=1,000,000
```{r}
results = read.delim("output/results_1000000/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", paste0("Fitness_", seq(0,970,by=10)))
```

Correlation with code robustness:
```{r}
cor.test(results$Robustness[2:100000], results$Fitness_500[2:100000])
```

Correct for global peak size:
```{r}
results = merge(results, res_size)

tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0],]
nrow(tmp_res)

(corTest = cor.test(tmp_res$Robustness, tmp_res$Fitness_500))
```