---
title: 'ParE2: Greedy walk, random codon assignment codes'
author: "Hana Rozhonova"
date: "6/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(ggplot2)
library(gridExtra)
library(ggpubr)
```

# Read the data
```{r}
if (file.exists("output/results_processed.tsv")) {
  results = read.delim("output/results_processed.tsv", header=TRUE)
} else {
  results = read.delim("output/results", header=FALSE, stringsAsFactors = FALSE)
  colnames(results) = c("Seed", "Robustness", "MeanFitness", "MeanSteps", "Peaks")
  
  # entropy of the reached peaks
  entropy_peaks = c()
  for (i in 1:nrow(results)) {
    peaks_counts = str_split(results$Peaks[i], ",")[[1]]
    peaks_counts = head(peaks_counts, -1)
    peaks_counts = as.numeric(lapply(str_split(peaks_counts, ":"), function(x) x[2]))
    # compute Shannon entropy
    peaks_probs = peaks_counts/sum(peaks_counts)
    entropy = -1*sum(peaks_probs*log(peaks_probs))
    entropy_peaks = c(entropy_peaks, entropy)
  }
  results$Entropy_peaks = entropy_peaks
  
  # probability of reaching the global peak
  prop = function(peaks, opt) {
    peaks_split = str_split(peaks, ",")[[1]]
    peak_opt = peaks_split[startsWith(peaks_split, opt)]
    peak_opt_count = sum(as.numeric(unlist(strsplit(peak_opt, ":"))[seq(2, 2*length(peak_opt), 2)]))
    count_total = 0
    for (peak in peaks_split[-length(peaks_split)]) {
      count_total = count_total + as.numeric(strsplit(peak, ":")[[1]][2])
    }
    return(peak_opt_count/count_total)
  }
  # global max
  data = read.delim("input/map.tsv", header=TRUE)
  global_max = as.character(data$sequence[which.max(data$phenotype)])
  results$Prob_reaching_global_peak = sapply(results$Peaks, prop, global_max)
  write.table(results, file="output/results_processed.tsv", quote=FALSE, sep="\t", row.names=FALSE)
}

```

# Histograms: Mean fitness, mean number of steps, entropy of the reached peaks, and probability of reaching the global peak(s)
```{r}
fit_standard = results$MeanFitness[results$Seed==0]
p = sum(results$MeanFitness>=fit_standard)/nrow(results)
hist_fit = ggplot(results, aes(x=MeanFitness)) + 
  geom_histogram(alpha=0.2, color="black") +
  theme_test() +
  geom_vline(xintercept=fit_standard, linetype="dashed", color="red") +
  labs(x="Mean fitness", y="Count", title=paste0("p=", signif(p, digits=3)))

steps_standard = results$MeanSteps[results$Seed==0]
p = sum(results$MeanSteps>=steps_standard)/nrow(results)
hist_steps = ggplot(results, aes(x=MeanSteps)) + 
  geom_histogram(alpha=0.2, color="black") +
  theme_test() +
  geom_vline(xintercept=steps_standard, linetype="dashed", color="red") +
  labs(x="Mean number of steps", y="Count", title=paste0("p=", signif(p, digits=3)))

ent_standard = results$Entropy_peaks[results$Seed==0]
p = sum(results$Entropy_peaks<=ent_standard)/nrow(results)
hist_ent = ggplot(results, aes(x=Entropy_peaks)) + 
  geom_histogram(alpha=0.2, color="black") +
  theme_test() +
  geom_vline(xintercept=ent_standard, linetype="dashed", color="red") +
  labs(x="Entropy of the distribution of reached peaks", y="Count", title=paste0("p=", signif(p, digits=3)))

prob_standard = results$Prob_reaching_global_peak[results$Seed==0]
p = sum(results$Prob_reaching_global_peak>=prob_standard)/nrow(results)
hist_prob = ggplot(results, aes(x=Prob_reaching_global_peak)) + 
  geom_histogram(alpha=0.2, color="black") +
  theme_test() +
  geom_vline(xintercept=prob_standard, linetype="dashed", color="red") +
  labs(x="Probability of reaching the global peak(s)", y="Count", title=paste0("p=", signif(p, digits=3)))

grid.arrange(hist_fit, hist_steps, hist_ent, hist_prob, ncol=2)
```



# Correlation with code robustness
```{r}
(corTest = cor.test(results$MeanFitness, results$Robustness))

(corTest = cor.test(results$MeanSteps, results$Robustness))

(corTest = cor.test(results$Entropy_peaks, results$Robustness))

(corTest = cor.test(results$Prob_reaching_global_peak, results$Robustness))

```


Restrict only to codes that have the same size of the global peak as the SGC and the global peak is not split:
```{r}
res_summitSizes = read.delim("../../02_ruggedness/random_codon_assignment/02_01_global_peak_size/results_globalPeakSize_random", header=FALSE)
colnames(res_summitSizes) = c("Seed", "SummitSize")
results = merge(results, res_summitSizes)

cor.test(results$MeanFitness, results$SummitSize)

tmp = results[results$SummitSize == results$SummitSize[results$Seed==0] ,]


(corTest = cor.test(tmp$MeanFitness, tmp$Robustness))
(corTest = cor.test(tmp$MeanSteps, tmp$Robustness))
(corTest = cor.test(tmp$Entropy_peaks, tmp$Robustness))
(corTest = cor.test(tmp$Prob_reaching_global_peak, tmp$Robustness))
```

