---
title: "Landscape ruggedness, random codon assignment codes, ParE3"
output: html_document
date: "2023-01-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(gridExtra)
library(stringr)
library(ggpubr)
```



```{r}
results = read.delim("output/results", header=FALSE)
colnames(results) = c("Seed", "Robustness", "NumPeaks", "MeanPeakHeight", "NoEpi", "MagEpi", "SsEpi", "RsEpi", "PropAccPaths")
```

# Number of peaks
```{r}
cor.test(results$Robustness[2:100000], results$NumPeaks[2:100000])
```

# Epistasis
#### No epistasis
```{r}
cor.test(results$Robustness[2:100000], results$NoEpi[2:100000])
```

#### Magnitude
```{r}
cor.test(results$Robustness[2:100000], results$MagEpi[2:100000])
```

#### Simple-sign
```{r}
cor.test(results$Robustness[2:100000], results$SsEpi[2:100000])
```

#### Reciprocal-sign
```{r}
cor.test(results$Robustness[2:100000], results$RsEpi[2:100000])
```

# Mutational accessibility
```{r}
cor.test(results$Robustness, results$PropAccPaths)

res_size = read.delim("02_01_global_peak_size/results_globalPeakSize_random", header=FALSE)
colnames(res_size) = c("Seed", "SummitSize")
results = merge(results, res_size)

# restrict the analysis to those codes that preserve the size of the global peak
tmp_res = results[results$SummitSize==results$SummitSize[results$Seed==0] ,]
nrow(tmp_res)

cor.test(tmp_res$Robustness, tmp_res$PropAccPaths)
```


